spring:
  application:
    name: JBlogWeb

  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jblog
    username: sa
    password: 

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true